// ==UserScript==
// @name         Angel Bypass
// @namespace    Angel.l0l bypass
// @version      1.2.0
// @description  Angel free userscript 
// @author       Angel.l0l
// @icon         https://cdn.discordapp.com/attachments/1472797429278703779/1489609882507153439/5C7558E7-2E1A-4F6B-9F19-464672F9D6D7.png?ex=69d10acf&is=69cfb94f&hm=3f3e588e5492cc1d6f035ea6ca3787ee3a3466baa8e0d904a5a9326ebd3aa344&
// @match        *://auth.platorelay.com/*
// @match        *://auth.platoboost.app/*
// @match        *://auth.platoboost.me/*
// @match        *://pandadevelopment.net/*
// @match        *://new.pandadevelopment.net/*
// @match        *://trigonevo.com/*
// @match        *://violated.lol/*
// @match        *://blox-script.com/*
// @match        *://boblox-script.com/*
// @match        *://hydrogen.lat/*
// @match        *://linkvertise.com/*
// @match        *://link-to.net/*
// @match        *://link-hub.net/*
// @match        *://link-target.org/*
// @match        *://link-target.net/*
// @match        *://link-center.net/*
// @match        *://direct-link.net/*
// @match        *://loot-link.com/*
// @match        *://lootdest.org/*
// @match        *://lootdest.com/*
// @match        *://lootlinks.co/*
// @match        *://lootdest.net/*
// @match        *://loot-links.com/*
// @match        *://direct-links.net/*
// @match        *://direct-links.org/*
// @match        *://linksloot.net/*
// @match        *://links.lootlabs.gg/*
// @match        *://links-loot.com/*
// @match        *://lootdest.info/*
// @match        *://lootlink.org/*
// @match        *://work.ink/*
// @match        *://workink.net/*
// @match        *://rinku.pro/*
// @match        *://7mb.io/*
// @match        *://mobile.codex.lol/*
// @match        *://stfly.vip/*
// @match        *://shrtslug.biz/*
// @match        *://lockr.so/*
// @match        *://lockr.net/*
// @match        *://linkunlocker.com/*
// @match        *://link-unlock.com/*
// @match        *://arolinks.com/*
// @match        *://tpi.li/*
// @match        *://go.linkify.ru/*
// @match        *://mboost.me/*
// @match        *://social-unlock.com/*
// @match        *://rekonise.com/*
// @match        *://rekonise.org/*
// @match        *://pastebin.com/*
// @match        *://paste-drop.com/*
// @match        *://pastefy.app/*
// @match        *://sub2unlock.com/*
// @match        *://sub2unlock.me/*
// @match        *://sub2unlock.io/*
// @match        *://sub4unlock.com/*
// @match        *://sub4unlock.me/*
// @match        *://sub4unlock.io/*
// @match        *://sub4unlock.pro/*
// @match        *://bstlar.com/*
// @match        *://scriptpastebins.com/*
// @match        *://paster.so/*
// @match        *://sfl.gl/*
// @match        *://go.yorurl.com/*
// @match        *://yorurl.com/*
// @match        *://www.robloxscripts.gg/*
// @match        *://lnbz.la/*
// @match        *://linkzy.space/*
// @match        *://ez4short.com/*
// @updateURL    https://raw.githubusercontent.com/ly5878259-cpu/Angel-early-access/main/userscript.js
// @downloadURL  https://raw.githubusercontent.com/ly5878259-cpu/Angel-early-access/main/userscript.js
// @require      https://raw.githubusercontent.com/ly5878259-cpu/Angel-early-access/main/main.js
// @grant        GM_setClipboard
// @grant        GM_openInTab
// @grant        GM_addStyle
// @grant        GM_xmlhttpRequest
// @connect      https://angel-userscript-api.vercel.app
// ==/UserScript==
