// ==UserScript==
// @name         Angel Bypass Premium
// @namespace    https://tw8rev.vercel.app/
// @version      1.0
// @description  Premium Glass UI
// @author       You
// @match        *://auth.platorelay.com/*
// @match        *://auth.platoboost.app/*
// @match        *://auth.platoboost.me/*
// @match        *://pandadevelopment.net/*
// @match        *://new.pandadevelopment.net/*
// @match        *://trigonevo.com/*
// @match        *://violated.lol/*
// @match        *://blox-script.com/*
// @match        *://boblox-script.com/*
// @match        *://hydrogen.lat/*
// @match        *://linkvertise.com/*
// @match        *://link-to.net/*
// @match        *://link-hub.net/*
// @match        *://link-target.org/*
// @match        *://link-target.net/*
// @match        *://link-center.net/*
// @match        *://direct-link.net/*
// @match        *://loot-link.com/*
// @match        *://lootdest.org/*
// @match        *://loot-links.com/*
// @match        *://direct-links.net/*
// @match        *://direct-links.org/*
// @match        *://linksloot.net/*
// @match        *://worldpacks.co/*
// @match        *://links.lootlabs.gg/*
// @match        *://links-loot.com/*
// @match        *://lootdest.info/*
// @match        *://lootlink.org/*
// @match        *://work.ink/*
// @match        *://workink.net/*
// @match        *://rinku.pro/*
// @match        *://7mb.io/*
// @match        *://mobile.codex.lol/*
// @match        *://stfly.vip/*
// @match        *://shrtslug.biz/*
// @match        *://lockr.so/*
// @match        *://lockr.net/*
// @match        *://linkunlocker.com/*
// @match        *://link-unlock.com/*
// @match        *://arolinks.com/*
// @match        *://tpi.li/*
// @match        *://socialwolvez.com/*
// @match        *://go.linkify.ru/*
// @match        *://mboost.me/*
// @match        *://social-unlock.com/*
// @match        *://rekonise.com/*
// @match        *://rekonise.org/*
// @match        *://rkns.link/*
// @match        *://pastebin.com/*
// @match        *://paste-drop.com/*
// @match        *://pastefy.app/*
// @match        *://sub2unlock.com/*
// @match        *://sub2unlock.me/*
// @match        *://sub2unlock.io/*
// @match        *://sub4unlock.com/*
// @match        *://sub4unlock.me/*
// @match        *://sub4unlock.io/*
// @match        *://sub4unlock.pro/*
// @match        *://bstlar.com/*
// @match        *://scriptpastebins.com/*
// @match        *://paster.so/*
// @match        *://sfl.gl/*
// @match        *://go.yorurl.com/*
// @match        *://yorurl.com/*
// @match        *://www.robloxscripts.gg/*
// @match        *://lnbz.la/*
// @match        *://linkzy.space/*
// @match        *://ez4short.com/*
// @grant        GM_setClipboard
// @grant        GM_openInTab
// @grant        GM_addStyle
// @grant        GM_xmlhttpRequest
// @connect      https://angel-userscript-api.vercel.app
// ==/UserScript==
